version: '3.3'
services:
    neo4j:
      image: neo4j
      hostname: neo4j
      container_name: neo4j
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes:
        - neo4jData:/data
        - neo4jConfig:/conf
        - neo4jPlugins:/plugins
        - neo4jLogs:/logs
      environment:
        NEO4J_AUTH: "neo4j/root"
    rabbitmq:
      image: rabbitmq:3.11.2-management-alpine
      container_name: rabbitmq
      ports:
          - 5672:5672
          - 15672:15672
      environment:
        - RABBITMQ_DEFAULT_USER=rabbitmq
        - RABBITMQ_DEFAULT_PASS=rabbitmq
  
volumes:
  neo4jData:
  neo4jConfig:
  neo4jLogs:
  neo4jPlugins: