version: '3'
services:
    neo4j:
      image: neo4j
      hostname: neo4j
      container_name: neo4j
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes:
        - ./neo4j/data:/data
        - ./neo4j/conf:/conf
        - ./neo4j/plugins:/plugins
        - ./neo4j/logs:/logs
      environment:
        NEO4J_AUTH: "neo4j/root"